### ISSUE TITLE
Misleading error wording when trying to envkey-source unauthorised ENVKEY

### ISSUE THREAD

**Issue by zbig-t** [envkey/envkey#10]
When you try to `envkey-source` an ENVKEY on unauthorised machine on which you don't have a corresponding `~/.envkey/apps/[APP_ID].env` file in place, the error message says `EnvKey CLI isn't installed or isn't in PATH` even when that's not the case instead of clearly explaining the root cause.

**Comment by danenania** [comment]
Thanks @zbig-t! Will get this fixed.

**Comment by danenania** [comment]
Should be fixed in 2.0.26
