### ISSUE TITLE
EnvKey logs not updating

### ISSUE THREAD

**Issue by miquelbrazil** [envkey/envkey#108]
My logs in the EnvKey app are not updating. When I click the Logs tab in the app, the most recent logs available are from nearly a month ago. To be sure, I can see activity in the log files located in the `~/.envkey/logs` directory, but these don't seem to correlate to the log data in the app. What can I do to correct this?

**Comment by miquelbrazil** [comment]
Because of the wind-down you've announced, I don't think keeping this issue open makes much sense. EnvKey was a great project; it's a shame to see it go. But I understand the challenge of maintaining a project totally (or mostly) solo.

I wish you the best of luck in your future endeavors.

**Comment by danenania** [comment]
Thank you @miquelbrazil, I appreciate the kind words and understanding.
