### ISSUE TITLE
Installer fails to add envkey tools to PATH on Windows 11

### ISSUE THREAD

**Issue by zbig-t** [envkey/envkey#11]
Even after confirming the UAC prompt during installation, `%USERPROFILE%\bin` doesn't get added to user's `PATH` automatically. Verified on Windows 11

![Screenshot 2022-05-03 165857](https://user-images.githubusercontent.com/70900625/166482065-79e30c84-b559-466c-8ed8-2ad4d5aff64e.png)
.

**Comment by danenania** [comment]
Hmm I'm not sure how feasible it is to modify permanent system environment variables like this on Windows. Need to research this more.

The hope is that in many cases, `%USERPROFILE%\bin` would already be in the `$PATH` but if it's not, we may need to leave it up to the user to add it. In any case, we could at least add something to the docs/installation output.

**Comment by zbig-t** [comment]
Oh, I see, I was under impression that EnvKey is trying to do that (adding the directory to PATH) while it is requesting elevated privileges with the UAC prompt and fails for some reason. In that case, I agree it would be nice for the installer to display some hint for the user to do this themselves.
