### ISSUE TITLE
Envkey 401ing in the desktop app.

### ISSUE THREAD

**Issue by Soldr** [envkey/envkey#13]
![image](https://user-images.githubusercontent.com/66232265/166874984-fd8efc26-74fa-410b-a84a-e8346c841e54.png)

**Comment by danenania** [comment]
Hi! Did you lock your device/set a passphrase?

Could you attach (or send to support@envkey.com) any files in `$HOME/.envkey/logs`? Thanks!

**Comment by danenania** [comment]
Sorted this out over email. Was an issue with WSL2.
