### ISSUE TITLE
Nodejs install brings packages for all environments - 66MB size

### ISSUE THREAD

**Issue by adityapatadia** [envkey/envkey#16]
When envkey is installed, it brings packages for all environments. Ideally it should bring the binary for given OS on which it's installed. Currently envkey package is biggest size in `node_modules` folder becasue of this
<img width="444" alt="Screenshot 2022-05-14 at 3 06 19 PM" src="https://user-images.githubusercontent.com/1086617/168420191-737d2ea2-6f76-47f7-b35e-a76a7aa06085.png">
.

**Comment by danenania** [comment]
Hey @adityapatadia, this is a deliberate tradeoff to make the SDKs work seamlessly cross-platform. While there may be some ways around this, I don't think any will be as simple and reliable as the current approach.

An alternative is using [envkey-source](https://docs-v2.envkey.com/docs/envkey-source) directly to avoid the extra weight.

**Comment by adityapatadia** [comment]
My idea was not to reduce the number of builds. Cross platform is super important. I know it would be little more work but downloding required binary at the time of installation like https://github.com/lovell/sharp would work best. Please consider in future releases.

If possible, please also provide instructions on how to use envkey-source inside node package.

**Comment by danenania** [comment]
> downloding required binary at the time of installation

I've considered it, but there are some potential edge cases with downloading at the time of installation, including use of bundlers and locked down networks, that have made me hesitant to go this route.

> If possible, please also provide instructions on how to use envkey-source inside node package.

To use envkey-source directly, you wouldn't need to call it from inside the package. You could just prefix your app start command like this:

```
$ envkey-source -- npm start
```

That would give you the same behavior as the node package. You could also add auto-reloads when a variable changes:

```
$ es -w -- npm start
```

(Using `es` alias here which is equivalent to `envkey-source`)

In development you can also tack on `-c` for local caching so you can keep working with a lost internet connection:

```
$ es -wc -- npm start
```
