### ISSUE TITLE
[v2] ENVKEY's Invalidating After Unknown Period of Time

### ISSUE THREAD

**Issue by hdwatts** [envkey/envkey#19]
We recently swapped to ENVKEY v2 and now our heroku apps are crashing after their daily restarts with `Invalid ENVKEY` errors. The environment variables and ENVKEY's have not changed, and have not been revoked. We resolved by individually regenerating the ENVKEYs and replacing them, which lead to a successful rebuild.

What is going on? Why are our ENVKEYs suddenly going invalid?

**Comment by danenania** [comment]
I think this is likely a relic of a bug that was fixed in a new release today. 

Now that you've regenerated the ENVKEYs, you shouldn't see this problem again, but please let me know if it continues from here.

**Comment by hdwatts** [comment]
@danenania Unfortunately a new issue is arising. Our ENVKEY's are loading and any environment variables that are set are loading properly. However, any variables that inherit from another environment are an empty string. Any idea what is happening here or how to rectify? I am on the latest version and I've tested regenerating the keys twice to no success.

**Comment by danenania** [comment]
That is most likely more fallout from the same bug. It caused the inherited values for some environments to be encrypted with the wrong key under certain conditions, which your org unfortunately happened to trigger. 

While I had thought that regenerating the ENVKEYs would be enough to re-encrypt these with the correct keys, it seems that a full update to the environment is needed. So if you have any other environments that are having this issue, go ahead and make an update--you can just add a variable, then commit, then delete the variable, then commit again.

**Comment by danenania** [comment]
Closing for now but will re-open if you see more problems @hdwatts
