### ISSUE TITLE
Variables frequently not loading on Mac App

### ISSUE THREAD

**Issue by flarco** [envkey/envkey#22]
Hi, I am using envkey for my Mac, and frequently, I open the app and the variables do not load for some of my applications.
I tried doing a `Force Reload` and closing/reopening envkey but no luck. Then I wait a few hours, and come back to it, and it works! Could you help me by suggesting what might be wrong? The CLI client works fine in fetching the vars always, but not the GUI.

**Comment by danenania** [comment]
Hi @flarco, could you zip up the files in ~/.envkey/logs and send them to support@envkey.com?

In the meantime, you can also try this as a workaround:
- Close the UI
- Run `envkey core stop` in a terminal
- Reopen the UI

**Comment by flarco** [comment]
Thanks, just sent.

**Comment by danenania** [comment]
This should now be fixed as of 1.2.1 of the UI/CLI, but please let me know if you see it pop up again and I'll re-open.
