### ISSUE TITLE
Received an error message of "api error: Both xsel and fallback failed" at the email confirmation step.

### ISSUE THREAD

**Issue by vonhuttri1990** [envkey/envkey#24]
I'm stuck at the email confirmation step. The error on the server returned is "api error: Both xsel and fallback failed".
![Screenshot 2022-09-12 at 16 32 40](https://user-images.githubusercontent.com/19265946/189621308-d9da6831-4c04-4178-aba2-a88768977951.png)

**Comment by danenania** [comment]
Hi, it looks like the server is missing a `NODE_ENV=production` environment variable, which causes it to copy the email token to the clipboard instead of sending the email (and the clipboard lib is failing to copy).

**Comment by vonhuttri1990** [comment]
After i try again with environment variable `NODE_ENV=production `aks it still gives the same error.
