### ISSUE TITLE
Error "DB migrations were unsuccessful"

### ISSUE THREAD

**Issue by vonhuttri1990** [envkey/envkey#25]
When i run env as development it doesn't get DB migration error, but when i run production it crashes:
`"DB migrations were unsuccessful.","alert":true,"err":{"name":"TypeError","message":"require.context is not a function","stack":"TypeError: require.context is not a function\n    at Object.runMigrationsIfNeeded (/opt/envkey/public/app/api/runtimes/express/src/migrate.ts:39:40)"}}`

**Comment by danenania** [comment]
Are you running form source or from the pre-compiled binary?

**Comment by danenania** [comment]
Looking at the code, this seems likely to be an issue with running from source.  We'll investigate further--in the meantime you could try running from the pre-compiled binary (more info here: https://docs-v2.envkey.com/docs/self-hosting-open-source-envkey)

**Comment by vonhuttri1990** [comment]
Yes. I run it from source.

**Comment by vonhuttri1990** [comment]
Is it necessary to consider the ```
NODE_ENV
``` environment variable when installing from the pre-compiled binary?

**Comment by danenania** [comment]
Nope, with the pre-compiled binary `NODE_ENV=production` is baked in. It does require some other env vars to be set though (see the docs linked above).

**Comment by vonhuttri1990** [comment]
Thanks..I have successfully run mail confirmation and created a new org. But I have the problem that when I invite people, they get "invite token" by mail and I send them directly an "Encryption token". But after they enter the above 2 tokens, the error is `"There was a problem loading and verifying your invite. Please ensure you copied both tokens correctly and try again."`. I make sure to double check those 2 tokens.
<img width="794" alt="Screenshot 2022-09-15 at 22 35 17" src="https://user-images.githubusercontent.com/19265946/190447306-21154cbf-55e4-46b1-a53b-f20aea825ebe.png">

**Comment by vonhuttri1990** [comment]
I send you the log file at the accept invite machine.
[desktop-2022-09-16.log.zip](https://github.com/envkey/envkey/files/9580990/desktop-2022-09-16.log.zip)

**Comment by danenania** [comment]
Could you please send the log file beginning with `core-`?

**Comment by vonhuttri1990** [comment]
I will send it by email, please check your inbox.
