### ISSUE TITLE
.env being ignored

### ISSUE THREAD

**Issue by nicholasareed** [envkey/envkey#26]
I'm running a create-react-app and have a `.env` file with values in it. My package.json's start script looks like: 
```
    "start": "envkey-source -- react-scripts start",
```

But my `.env` values are ignored, in favor of the values I have set in my EnvKey. When I remove the key/value from EnvKey (in the UI), the `.env` file's value is used...

Documentation says that my local `.env` values should take precedence. Is that incorrect?

**Comment by danenania** [comment]
Hi, looking into this! You're right that `.env` values should be taking precedence.

In the meantime, you could also try [local overrides](https://docs-v2.envkey.com/docs/branches-and-local-overrides#local-overrides)

**Comment by danenania** [comment]
Should now be fixed in envkey-source 2.0.27
