### ISSUE TITLE
Production Trusted IPs does not allow enough IPs

### ISSUE THREAD

**Issue by dbsanfte** [envkey/envkey#39]
Hiya,

We have a use case for more than the 20 or so IPs that Production Trusted IPs currently supports on our org.

This worked fine in Envkey1. Envkey2 seems to limit it for some reason. Is this a technical limitation or a UI one?

Also, can this be changed back to a freetext field please? It is laborious to enter them one at a time and it's easy to fat-finger a deletion and not know which one you've deleted, and then you have to hunt for it... just a pain all around :)

**Comment by dbsanfte** [comment]
The description on the Org Firewall page says "add any number of IPV4/IPV6 ranges" so going to assume this is a UI bug. Try adding more than 20 or so CIDR ranges and you'll see what I mean, the UI stops you from entering any more.

Also copy/paste from envkey1 to envkey2 doesn't work, you'll again see what I mean if you try it.

**Comment by danenania** [comment]
You're right that for practical purposes there shouldn't be a limit. We do need a sanity-check upper limit but we can definitely make it higher (assuming that's what you're running into--I'll have to confirm). Could you give me a ballpark on how many you need to add?

We'll also see what can be done about adding back copy-paste support or just going back to free-form entry. Thanks for the feedback on that.

**Comment by danenania** [comment]
Copy-paste for these fields is now supported in 2.2.3. We couldn't reproduce the limit on IPs/CIDRs. They should be unlimited. Is it possible you were trying to add a duplicate value?

In any case, let me know if you're still seeing that and I'll re-open.

**Comment by dbsanfte** [comment]
This works now, thanks.
