### ISSUE TITLE
how to call  `envkey.fetch_env`  in envkey2?

### ISSUE THREAD

**Issue by jdeflaux** [envkey/envkey#40]
How can we call `envkey.fetch_env` with the envkey value passed as parameter?

As documented, it should be like in v1:
```python
import envkey
import os

config = envkey.fetch_env(os.environ['ENVKEY'], cache_enabled=True)
```

However I can see that it now accepts only the optional parameter `cache_enabled`, but not the envkey value anymore.
https://github.com/envkey/envkey/blob/dd1e09c42d3fb802bd46db7b71e3a49cb18ad2ad/public/sdks/languages-and-frameworks/python/pkg/envkey/fetch.py#L48

I may have missed something obvious 🤔 or is there an alternative?  

thanks,

**Comment by danenania** [comment]
Hi @jdeflaux, the `ENVKEY` is now read from an environment variable instead of an argument, so there shouldn't be a need to pass in the parameter. 

Does this work for you? 👇

```
config = envkey.fetch_env(cache_enabled=True)
```

**Comment by danenania** [comment]
This function is now backward compatible as of 2.1.2 of the python package.
