### ISSUE TITLE
Adding variables to block doesn't show up in UI

### ISSUE THREAD

**Issue by emandakh** [envkey/envkey#41]
Version: 2.2.3
OS: Windows 10, 10.0.19044 Build 19044

Repro: 
- create a new block
- add variable to block
- commit the changes with a message
- variables don't show up immediately in UI, looks as if block is empty
- the added variables only show up if envkey is reloaded with Ctrl+R

May or may not be related, but I have a new 4th environment on top of dev, staging and prod that's linked to all blocks.

**Comment by danenania** [comment]
Thanks @emandakh, we're investigating this, along with the other issues you posted.

**Comment by emandakh** [comment]
Awesome, thanks @danenania !

**Comment by danenania** [comment]
This should now be fixed as of 2.2.5
