### ISSUE TITLE
Multi-line edit mode doesn't work when opening block vars from app

### ISSUE THREAD

**Issue by emandakh** [envkey/envkey#42]
Version: 2.2.3
OS: Windows 10, 10.0.19044 Build 19044

Repro:
- create a block with variable and value that's very long
- connect above block to an app
- open the long value block var from the app
- the multi-line editor will fail to show the values

The multi-line editor only fails if you open the block var from an app.  If you open the block var from the block menu it works fine.

Also I have a new 4th env connected to all blocks and apps, not sure if that matters.

**Comment by danenania** [comment]
This should now be fixed as of 2.2.5
