### ISSUE TITLE
Can't order new environment at front

### ISSUE THREAD

**Issue by emandakh** [envkey/envkey#43]
Version: 2.2.3
OS: Windows 10, 10.0.19044 Build 19044

Repro:
- create a new 4th env, I called it local
- go to manage environments menu
- order the new env such that it's at the top, above "development"
- this causes the env to appear at the back, after "production" instead, when it should appear before "development" env

If you put the new env in between "development" or "staging" or at the end of "production" the order seems to work fine.

**Comment by danenania** [comment]
This should now be fixed as of 2.2.5
