### ISSUE TITLE
local .env broken (again)

### ISSUE THREAD

**Issue by nicholasareed** [envkey/envkey#46]
It seems like recent changes have caused the local `.env` file to be ignored. 

It is extremely frustrating that we can simply upgrade, and lose core functionality like _respect the local .env file that the company is named after_. 

Local overrides are _not_ the answer, they are simply too unwieldy to manage in the UI as compared to a local .env file.

**Comment by danenania** [comment]
We're investigating this.

I understand bugs are frustrating. Believe me, they're frustrating for us too. That said, please keep the tone here professional and respectful. That's how we treat our users, customers, vendors, and everyone else we do business with (including when there are bugs and problems). We expect the same in return.

**Comment by danenania** [comment]
Is the `ENVKEY` set in your `.env` file or set by an environment variable? Or do you have a `.envkey` file in the directory?
