### ISSUE TITLE
ENVKEY not found if cwd is a subdirectory

### ISSUE THREAD

**Issue by colvin** [envkey/envkey#49]
If executing a process within a subdirectory of an app the ENVKEY will not be found.

I see the ENVKEY load order [here](https://github.com/envkey/envkey/blob/a53eb1212e832f169123ac49fcc6eed308bf0f57/public/sdks/envkey-source/env/env.go#L34). There is a pretty standard practice (eg Git) of scanning upwards through the directory structure for config files, stopping at the filesystem root.

The load order could look something like this:
1. ENVKEY environment variable is set
2. `.env` file in the current directory (or `--env-file` override)
3. `.env` file in a parent directory
4. `.envkey` config file in current directory + file at `~/.envkey/apps/[appId].env`
5. `.envkey` config file in a parent directory + file at `~/.envkey/apps/[appId].env`
6. `~/.env`
7. Bail

This would allow me to run EnvKey integrated commands from anywhere within my app's directory structure.

I'm not positive, but anecdotally I recall being able to do this with the Node SDK in EnvKey 1. I noticed when upgrading to EnvKey 2 that the Node SDK lost its dependence on `dotenv` (presumably because this is handled by `envkey-source` now) so that could have been `dotenv`'s behavior.

**Comment by danenania** [comment]
Thanks for the suggestion and laying out your thinking. I think this is a good idea and it would definitely make it more convenient for dealing with commands in subdirectories. 

My only hesitation is that it could create some tricky situations in projects that use ENVKEYs at multiple levels of a project hierarchy. Say you have one ENVKEY at `/project` and then another ENVKEY at `/project/sub`. Now if the ENVKEY at `/project/sub` gets removed, you'll load the wrong ENVKEY, which could be difficult to realize and debug.

I'm not sure this outweighs the convenience of running commands in subdirectories, as it's a bit of a niche concern and probably not the most advisable way to lay out a project anyway, but it does create a potential sharp edge.  Some `dotenv` libraries do look upward and some don't, which perhaps reflect a split in how people are weighing the tradeoff.

Overall I'm leaning towards going with your suggestion, but need to think through it a little bit more.

**Comment by danenania** [comment]
@colvin Ok, it took awhile to get to this, but it's now live in 2.4.0 of envkey-source and all the language libraries.

Here's the precedence--pretty much the same as what you proposed. 

## ENVKEY / .env file / .envkey file resolution order and precedence

1. `ENVKEY` environment variable has highest precedence.

2. If `ENVKEY` environment variable unset, `--env-file` parameter is checked and takes precedence if so.

3. If neither `ENVKEY` environment variable or `--env-file` is set, the library searches for either a `.env`(with an `ENVKEY` set)  or a `.envkey` file (JSON with `orgId` and `appId` set), starting in the current directory then checking recursively upwards. The file found at the lowest depth (i.e., closest to the current directory) is chosen. If both files are found at the same depth, the `.env` file takes precedence.

4. If an `.envkey` or `.env` file with an `ENVKEY` set in it still hasn't been found, check  for`.env` with `ENVKEY` present at `~/.env`.

5. If `.env` _without_ `ENVKEY` is found, overrides are still applied, unless an existing environment variable is already set, in which case that takes precedence. If an `.envkey` is found, no further lookup for `.env` above this location occurs.

☝️The above has now been added to docs for envkey-source and all language libs.
