### ISSUE TITLE
Super slow update

### ISSUE THREAD

**Issue by sscarduzio** [envkey/envkey#5]
I'm stuck one hour on this sloooow progress bar. The network speed monitor is ~0KB/s. Not sure why so slow?

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/1327189/163583011-89e269d7-8378-4a69-b4b4-de7fdfea44cf.png">

**Comment by danenania** [comment]
@sscarduzio Did you have the same problem with the latest update? Closing for now but will re-open if you're still experiencing this. Would need those logs to diagnose.

**Comment by sscarduzio** [comment]
FYI, 5 days ago it eventually crashed at 80% after looooong time. The logs of that day: 

https://gist.github.com/sscarduzio/a899d0be6e1ab4a3a16956c452f4903b


New version upgrade worked well (to 2.0.49).
