### ISSUE TITLE
I can't upgrade for weeks

### ISSUE THREAD

**Issue by ricardo-lopes** [envkey/envkey#50]
From the UI, i can't upgrade for weeks. Application crashes.
A clean install (or so I think it is clean after deleting some folders) still brings up an upgrade message, but for cli only.
CLI upgrade crashes too.

From the logs:
{"ts":"2023-02-22T10:18:51.230Z","msg":"EnvKey CLI upgrade: unpacked to folder","folder":"C:\\Users\\R82BD~1.LOP\\AppData\\Local\\Temp\\envkey_1677061129.35"}
{"ts":"2023-02-22T10:18:51.231Z","msg":"first kill core process and move to inline prior to upgrade"}
{"ts":"2023-02-22T10:18:51.240Z","msg":"GET /stop"}

not sure how to kill the core process.

**Comment by jdeflaux** [comment]
I have the same problem, envkey UI cannot upgrade. 

I am stuck with the version 2.2.10.

If I click "upgrade all" the applications restarts, stays in the same version, and prompts me to upgrade again.

**Comment by danenania** [comment]
Hi @ricardo-lopes and @jdeflaux, we're investigating this.

**Comment by danenania** [comment]
This should be fixed in the latest UI release (2.2.13). Since upgrades aren't working for you, you can install the latest version from https://envkey.com
