### ISSUE TITLE
Output vars without quotes

### ISSUE THREAD

**Issue by manuelmeurer** [envkey/envkey#52]
I just updated to v2 and I'm trying to load my env vars in a Github Action.
To do so, one is supposed to [add them to a file](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable) like this:
`echo "key=value" >> $GITHUB_ENV`

I tried doing it via `echo "$(envkey-source --dot-env)" >> $GITHUB_ENV` but unfortunaly the `--dot-env` format adds single quotes around the values.

Would it be possible to add another format (`--env` maybe?) that prints them like `--dot-env` but without the quotes?
This would be perfect for the Github Actions use case.

**Comment by danenania** [comment]
Hi @manuelmeurer, stripping the quotes from within envkey-source would create a potential shell injection vulnerability, since the output is being passed to eval. You could try this instead:

echo "$(envkey-source --dot-env)" | tr -d "'" >> $GITHUB_ENV

**Comment by danenania** [comment]
Actually, it's better to remove the `$()` completely, since with the `--dot-env` flag keys are unquoted, so still not a good idea to pass that output to `$()`. You could just do:

```
envkey-source --dot-env | tr -d "'" >> $GITHUB_ENV
```

**Comment by danenania** [comment]
Closing for now, but happy to re-open and find a solution if the above doesn't work for you.
