### ISSUE TITLE
Crypto Upgrade Required

### ISSUE THREAD

**Issue by Rizbe** [envkey/envkey#55]
![image_2023-03-20_17-00-53](https://user-images.githubusercontent.com/16785429/226466970-fcc54722-643b-4140-895f-3f0ce667d93a.png)

I tried to recover my org, but when I get to the screen to add my computer name and sign in, I get the error Crypto upgrade required tried on Windows and Linux.

**Comment by Rizbe** [comment]
Seems like if I make a new org it works but can't restore my old account

**Comment by danenania** [comment]
Hi, we're investigating. Has it been awhile since you signed into this org before trying to recover?

**Comment by Rizbe** [comment]
It's been awhile, probably a few months.

**Comment by danenania** [comment]
Closing for now @Rizbe since I haven't heard from you, but please let me know if you get a chance to try again and it's still not working.
