### ISSUE TITLE
Node SDK ignores the dotEnvFile configuration parameter

### ISSUE THREAD

**Issue by jar0s** [envkey/envkey#56]
In the latest version (2.3.0) of [node library](https://github.com/envkey/envkey/tree/main/public/sdks/languages-and-frameworks/node), the `dotEnvFile` confguration parameter, which is described in[ its docs](https://github.com/envkey/envkey/tree/main/public/sdks/languages-and-frameworks/node#custom-loading), is ignored (as in never added to the [execArgs](https://github.com/envkey/envkey/blob/main/public/sdks/languages-and-frameworks/node/pkg/loader.js#L138) array) and never passed to the call of the underlying envkey-source binary.
This results in the `ENVKEY missing` error when trying to use that option.

**Comment by jar0s** [comment]
Adding the below code before `execFile()` within the `fetch()` function seems to be solving the issue.
```
if (opts.dotEnvFile) {
    execArgs.push('--env-file')
    execArgs.push(opts.dotEnvFile)
  }
```

**Comment by danenania** [comment]
Hi @jar0s, we'll get this fixed shortly

**Comment by danenania** [comment]
Fixed in 2.3.1

**Comment by jar0s** [comment]
Thank you for an express turnaround on this @danenania.
Really appreciate it.

**Comment by danenania** [comment]
Sure thing @jar0s!
