### ISSUE TITLE
envkey-source-v2 is not able to source a custom ENVKEY value

### ISSUE THREAD

**Issue by claytongroth** [envkey/envkey#58]
In V1 of ENVKEY, this was possible:

```shell
#!/bin/bash
eval $(envkey-source <<ENVKEY_HERE>>)

echo $SOME_VAR_FROM_ENVKEY
```
This allowed me to pass a **certain** ENVKEY value in place of `ENVKEY_HERE`, say from a different path,
Is there a way to do that in ENVKEY V2?

I am able to 
```shell
#!/bin/bash
eval $(envkey-source)

echo $SOME_VAR_FROM_ENVKEY
```
But this works only off of `~/.env`

```shell
#!/bin/bash
eval $(envkey-source-v2  <<ENVKEY_HERE>>)

echo $SOME_VAR_FROM_ENVKEY
```

Results in an error as it appears not to take that argument anymore.

**Comment by danenania** [comment]
Hi @claytongroth, rather than passing your `ENVKEY` as an argument, you can accomplish the same in V2 by setting it as an environment variable prior to the `eval` call:

```
#!/bin/bash
ENVKEY=<<ENVKEY_HERE>> eval "$(envkey-source-v2)"
echo $SOME_VAR_FROM_ENVKEY
```

**Comment by claytongroth** [comment]
@danenania Thanks for the quick help on these issues!

**Comment by danenania** [comment]
Sure thing @claytongroth!
