### ISSUE TITLE
Expand variables / Variables in Variables

### ISSUE THREAD

**Issue by matzeeable** [envkey/envkey#60]
Hey!

Awesome tool! This looks very promising. 😊

I just registered and wanted to test the first things to move our local `.env` to EnvKey. The CLI works great, especially with the `--mem-cache` parameter, top!

Unfortunately I ran into a first problem: Variables in variables. I already found this: https://docs-v2.envkey.com/docs/branches-and-local-overrides#local-environment-variables, but it does not resolve my issue.

Given the following example:

![image](https://user-images.githubusercontent.com/1008534/233325115-c734463c-62a7-4df9-8eb1-24bc5fa5405b.png)

As you can see, I have a variable `HOSTS_API` with `commerce.$ENVIRONMENT_BASE_HOSTNAME`. In my local `.env-new` I have the "required" variable `ENVIRONMENT_BASE_HOSTNAME` defined.

When running `envkey-source --env-file .env-new --dot-env` it does not expand the variable to `commerce.my-local-machine.example.com`.

Is there something like a `--expand-variables` CLI argument which resolves variables in variables?

**Comment by danenania** [comment]
Hi @matzeeable good to hear that it's working well for you so far! EnvKey doesn't support referencing other variables like this. You'd have to handle it on the application side.

I'd suggest setting the subdomain in your block with a `HOSTS_API_SUBDOMAIN` variable, then in your application you can concatenate. I don't know what language you're using, but in javascript, for example, it would look like:

```
const host = `${process.env.HOSTS_API_SUBDOMAIN}.${process.env.ENVIRONMENT_BASE_HOSTNAME}`
```
