### ISSUE TITLE
Envkey v2 cannot start after deleting user

### ISSUE THREAD

**Issue by trungklam** [envkey/envkey#64]
Hi Dane, I'm currently using a self-hosting Envkey v2. Recently, I deleted some user that is not belong to our organization, then the envkey client got stuck and cannot start. I tried to reload and force reload and the issue is still happen. It look like there might be something wrong with the database but I cannot manage to check
Here is the log from client 
![image](https://github.com/envkey/envkey/assets/17236895/384a0660-f056-4ee9-a86d-5f72b9a9d824)

**Comment by trungklam** [comment]
I managed to fix this by doing the following steps:
- Uninstall and install envkey v2 again (to clear all cache)
- After reinstalling, the issue still happen then I use the envkey cli to sign in`envkey.exe sign-in` then re-open the client app - it works :)
For windows users, you can fine the CLI at C:\Users\<username>\AppData\Local\Programs\envkey\resources\app\bin\windows

**Comment by danenania** [comment]
Hi @trungklam, glad to hear you got this resolved. We're investigating the underlying issue. What version of EnvKey Community OSS API are you running on the server?

**Comment by trungklam** [comment]
> Hi @trungklam, glad to hear you got this resolved. We're investigating the underlying issue. What version of EnvKey Community OSS API are you running on the server?

Hi @danenania , I'm using 2.3.1 for the OSS API , client GUI and CLI are latest.
Also, does the client GUI support the `envkey sign-in` somewhere ? I couldnt find it from UI so when log-out I have to use CLI to login back. It's not actually an issue but I think it can be more intuitive if I can re-login from UI
