### ISSUE TITLE
[API] Please, provide an environment variable to set the IP address to listen to

### ISSUE THREAD

**Issue by ldidry** [envkey/envkey#84]
Currently, when you launch the API, it listen on all IP addresses.

It would be useful to be able to set an env var like `EXPRESS_IP` to change that.
It would avoid the burden to setup a firewall if you don’t already have one.

**Comment by danenania** [comment]
Thanks @ldidry this will be added shortly

**Comment by danenania** [comment]
Added in [df28bca](https://github.com/envkey/envkey/commit/df28bcab02c38b186aaa7418327a7f3a9a905a3a), you can now set `EXPRESS_IP` environment variable.

**Comment by ldidry** [comment]
Thx!
