### ISSUE TITLE
envkey GUI can't connect to API server

### ISSUE THREAD

**Issue by Erkak** [envkey/envkey#87]
Hello,
Envkey GUI 2.4.13 (Windows edition) can't connect to API server during creation of new organiztion due to the following error: 
{"ts":"2023-09-05T11:02:38.735Z","proc":"main","msg":"[ui-console] Problem sending Email Token:","type":"clientError","error":{"name":"RequestError","message":"unable to verify the first certificate"}}

API server has self-signed sertificate. 
I imported certificate into operating system where Envkey GUI is running but it didn't help. 
So how to make Envkey GUI trust self-signed certificate or ignore it?!

**Comment by danenania** [comment]
Hi @Erkak,

To run EnvKey with custom certs:

1. set NODE_EXTRA_CA_CERTS=<FILE_PATH>
where you replace <FILE_PATH> with an absolute path that points to your certificate file (for example, C:\folder\subfolder\certificate.pem on Windows).

2. You can test whether this works by setting these variables in a terminal, then running `envkey core start --inline`, then opening the EnvKey UI.

To disable SSL verification, you can set NODE_TLS_REJECT_UNAUTHORIZED=0 (but it's not recommended).
