### ISSUE TITLE
EnvKey 2.4.16 doesn't start anymore

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey#94]
System: Microsoft Windows, Version 22H2 (OS Build 19045.3570)

After update to envkey 2.4.16 the app doesn't startup anymore.

![image](https://github.com/envkey/envkey/assets/462013/36175ea2-5c64-458a-b9b0-d3cac52eeae5)

![envkey-issue](https://github.com/envkey/envkey/assets/462013/392ebe6c-848d-41ac-a7df-eb0245379b2e)

How can I help to resolve the issue?

**Comment by danenania** [comment]
Hi @SeriousM, we're investigating. I'll get back to you shortly on this.

Could you please run `envkey core report-error` in a terminal to send us recent logs?

**Comment by SeriousM** [comment]
> Could you please run `envkey core report-error` in a terminal to send us recent logs?

I've executed the cli, I guess the report is sent to you behind the scenes? (maybe an info would help)

**Comment by danenania** [comment]
This should now be resolved in 2.4.17
