### ISSUE TITLE
High database usage due to logs

### ISSUE THREAD

**Issue by matzeeable** [envkey/envkey#98]
Hey!

We got an alert in our monitoring that the envkey database is getting out of disk. Then, I checked the database tables and the `transaction_ids_by_target_id` has more than 12 GB.

![image](https://github.com/envkey/envkey/assets/1008534/d79a5722-064a-4a5e-81be-b88ca7049e66)

Doing some research, I found out this is the [Audit log](https://docs-v2.envkey.com/docs/audit-logs). We are using the [Open Source community installation](https://docs-v2.envkey.com/docs/self-hosting-open-source-envkey).

What happens if we just truncate the table?

Is there are way to configure something like a log rotation to delete logs after 30 days?

Thanks! 😊

**Comment by danenania** [comment]
Hi @matzeeable, there is no log rotation built in currently, but yes you can feel free to delete all rows with `createdAt` older than whatever date you want from `transaction_ids_by_target_ids`--this table is used only for filtering logs.
